# Generated by Django 3.1.4 on 2020-12-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_date', models.CharField(max_length=300)),
                ('event_price', models.CharField(max_length=30)),
                ('event_venue', models.CharField(max_length=300)),
                ('event_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InterestingURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NotInterestingURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_interesting_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YogaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('postcode', models.CharField(max_length=264)),
                ('qualification', models.CharField(max_length=264)),
                ('vision', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
